disabled_rules:
    - line_length
    - force_cast
    - unused_optional_binding
    - unused_closure_parameter


excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
